<a href="https://colab.research.google.com/github/UmidjonDev/Artificial_Intelligence_Related/blob/main/Copy_of_03_PANDAS_yakuniy_vazifa_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

![Imgur](https://i.imgur.com/5pXzCIu.png)

# Data Science va Sun'iy Intellekt Praktikum

## Ma'lumotlar tahlili. Pandas kutubxonasi.

### PANDAS. Yakuniy vazifa. **2-Qism**

## Dataset
#### Ushbu vazifada biz turli davlatlarning turli yillarda elektr tokini qanday manbaalardan olganini ko'rsatuvchi jadval bilan ishlaymiz.
Jadval ustunlari ko'mir, gaz, gidro va boshqa manbaalardan ko'rsatilgan yilda qancha __terravat/soat__ energiya olinganini ko'rsatadi.

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("https://raw.githubusercontent.com/anvarnarz/praktikum_datasets/main/Electricity_Production_By_Source.csv")
df.columns = ['davlat','kod','yil','komir','gaz','gidro','yangilanuvchi','quyosh','neft','shamol','atom']
df.head()

,davlat,kod,yil,komir,gaz,gidro,yangilanuvchi,quyosh,neft,shamol,atom
0,Afghanistan,AFG,2000,0.0,0.155,0.312,0.0,0.0,0.0,0.0,0.0
1,Afghanistan,AFG,2001,0.0,0.094,0.498,0.0,0.0,0.0,0.0,0.0
2,Afghanistan,AFG,2002,0.0,0.132,0.555,0.0,0.0,0.0,0.0,0.0
3,Afghanistan,AFG,2003,0.0,0.309,0.630,0.0,0.0,0.0,0.0,0.0
4,Afghanistan,AFG,2004,0.0,0.329,0.565,0.0,0.0,0.0,0.0,0.0

### 1-VAZIFA. DF hajmini chiqaring

In [4]:
# JAVOBNI SHUYERGA YOZING
df.shape

(6241, 11)

### 2-VAZIFA. Jadvalda mavjud davlatlar ro'yxatini alohida chiqaring

In [5]:
# JAVOBNI SHUYERGA YOZING
print(df["davlat"].unique())

['Afghanistan' 'Africa' 'Albania' 'Algeria' 'American Samoa' 'Angola'
 'Antarctica' 'Antigua and Barbuda' 'Argentina' 'Armenia' 'Aruba'
 'Asia Pacific' 'Australia' 'Austria' 'Azerbaijan' 'Bahamas' 'Bahrain'
 'Bangladesh' 'Barbados' 'Belarus' 'Belgium' 'Belize' 'Benin' 'Bermuda'
 'Bhutan' 'Bolivia' 'Bosnia and Herzegovina' 'Botswana' 'Brazil'
 'British Virgin Islands' 'Brunei' 'Bulgaria' 'Burkina Faso' 'Burundi'
 'CIS' 'Cambodia' 'Cameroon' 'Canada' 'Cayman Islands'
 'Central African Republic' 'Central America' 'Chad' 'Chile' 'China'
 'Colombia' 'Comoros' 'Congo' 'Cook Islands' 'Costa Rica' 'Croatia' 'Cuba'
 'Cyprus' 'Czechia' 'Democratic Republic of Congo' 'Denmark' 'Djibouti'
 'Dominica' 'Dominican Republic' 'EU-27' 'EU27+1' 'Eastern Africa'
 'Ecuador' 'Egypt' 'El Salvador' 'Equatorial Guinea' 'Eritrea' 'Estonia'
 'Ethiopia' 'Europe' 'Europe (other)' 'Falkland Islands' 'Faroe Islands'
 'Fiji' 'Finland' 'France' 'French Guiana' 'French Polynesia' 'Gabon'
 'Gambia' 'Georgia' 'Germany' 'Ghana' 'Gibraltar' 'Greece' 'Greenland'
 'Grenada' 'Guadeloupe' 'Guam' 'Guatemala' 'Guinea' 'Guinea-Bissau'
 'Guyana' 'Haiti' 'Honduras' 'Hong Kong' 'Hungary' 'Iceland' 'India'
 'Indonesia' 'Iran' 'Iraq' 'Ireland' 'Israel' 'Italy' 'Jamaica' 'Japan'
 'Jordan' 'Kazakhstan' 'Kenya' 'Kiribati' 'Kosovo' 'Kuwait' 'Kyrgyzstan'
 'Laos' 'Latvia' 'Lebanon' 'Lesotho' 'Liberia' 'Libya' 'Lithuania'
 'Luxembourg' 'Macau' 'Madagascar' 'Malawi' 'Malaysia' 'Maldives' 'Mali'
 'Malta' 'Martinique' 'Mauritania' 'Mauritius' 'Mexico' 'Middle Africa'
 'Middle East' 'Moldova' 'Mongolia' 'Montenegro' 'Montserrat' 'Morocco'
 'Mozambique' 'Namibia' 'Nauru' 'Nepal' 'Netherlands'
 'Netherlands Antilles' 'New Caledonia' 'New Zealand' 'Nicaragua' 'Niger'
 'Nigeria' 'Niue' 'North America' 'North Korea' 'North Macedonia' 'Norway'
 'Oman' 'Other Asia & Pacific' 'Other CIS' 'Other Caribbean'
 'Other Middle East' 'Other Northern Africa' 'Other South America'
 'Other Southern Africa' 'Pakistan' 'Palestine' 'Panama'
 'Papua New Guinea' 'Paraguay' 'Peru' 'Philippines' 'Poland' 'Portugal'
 'Puerto Rico' 'Qatar' 'Reunion' 'Romania' 'Russia' 'Rwanda'
 'Saint Helena' 'Saint Kitts and Nevis' 'Saint Lucia'
 'Saint Pierre and Miquelon' 'Saint Vincent and the Grenadines' 'Samoa'
 'Sao Tome and Principe' 'Saudi Arabia' 'Senegal' 'Serbia' 'Seychelles'
 'Sierra Leone' 'Singapore' 'Slovakia' 'Slovenia' 'Solomon Islands'
 'Somalia' 'South & Central America' 'South Africa' 'South Korea'
 'South Sudan' 'Spain' 'Sri Lanka' 'Sudan' 'Suriname' 'Sweden'
 'Switzerland' 'Syria' 'Taiwan' 'Tajikistan' 'Tanzania' 'Thailand' 'Togo'
 'Tonga' 'Trinidad and Tobago' 'Tunisia' 'Turkey' 'Turkmenistan'
 'Turks and Caicos Islands' 'U.S. Pacific Islands' 'Uganda' 'Ukraine'
 'United Arab Emirates' 'United Kingdom' 'United States'
 'United States Virgin Islands' 'Uruguay' 'Uzbekistan' 'Vanuatu'
 'Venezuela' 'Vietnam' 'Western Africa' 'Western Sahara' 'World' 'Yemen'
 'Zambia' 'Zimbabwe']

In [ ]:
#@title Kutilgan natija

array(['Afghanistan', 'Africa', 'Albania', 'Algeria', 'American Samoa',
       'Angola', 'Antarctica', 'Antigua and Barbuda', 'Argentina',
       'Armenia', 'Aruba', 'Asia Pacific', 'Australia', 'Austria',
       'Azerbaijan', 'Bahamas', 'Bahrain', 'Bangladesh', 'Barbados',
       'Belarus', 'Belgium', 'Belize', 'Benin', 'Bermuda', 'Bhutan',
       'Bolivia', 'Bosnia and Herzegovina', 'Botswana', 'Brazil',
       'British Virgin Islands', 'Brunei', 'Bulgaria', 'Burkina Faso',
       'Burundi', 'CIS', 'Cambodia', 'Cameroon', 'Canada',
       'Cayman Islands', 'Central African Republic', 'Central America',
       'Chad', 'Chile', 'China', 'Colombia', 'Comoros', 'Congo',
       'Cook Islands', 'Costa Rica', 'Croatia', 'Cuba', 'Cyprus',
       'Czechia', 'Democratic Republic of Congo', 'Denmark', 'Djibouti',
       'Dominica', 'Dominican Republic', 'EU-27', 'EU27+1',
       'Eastern Africa', 'Ecuador', 'Egypt', 'El Salvador',
       'Equatorial Guinea', 'Eritrea', 'Estonia', 'Ethiopia', 'Europe',
       'Europe (other)', 'Falkland Islands', 'Faroe Islands', 'Fiji',
       'Finland', 'France', 'French Guiana', 'French Polynesia', 'Gabon',
       'Gambia', 'Georgia', 'Germany', 'Ghana', 'Gibraltar', 'Greece',
       'Greenland', 'Grenada', 'Guadeloupe', 'Guam', 'Guatemala',
       'Guinea', 'Guinea-Bissau', 'Guyana', 'Haiti', 'Honduras',
       'Hong Kong', 'Hungary', 'Iceland', 'India', 'Indonesia', 'Iran',
       'Iraq', 'Ireland', 'Israel', 'Italy', 'Jamaica', 'Japan', 'Jordan',
       'Kazakhstan', 'Kenya', 'Kiribati', 'Kosovo', 'Kuwait',
       'Kyrgyzstan', 'Laos', 'Latvia', 'Lebanon', 'Lesotho', 'Liberia',
       'Libya', 'Lithuania', 'Luxembourg', 'Macau', 'Madagascar',
       'Malawi', 'Malaysia', 'Maldives', 'Mali', 'Malta', 'Martinique',
       'Mauritania', 'Mauritius', 'Mexico', 'Middle Africa',
       'Middle East', 'Moldova', 'Mongolia', 'Montenegro', 'Montserrat',
       'Morocco', 'Mozambique', 'Namibia', 'Nauru', 'Nepal',
       'Netherlands', 'Netherlands Antilles', 'New Caledonia',
       'New Zealand', 'Nicaragua', 'Niger', 'Nigeria', 'Niue',
       'North America', 'North Korea', 'North Macedonia', 'Norway',
       'Oman', 'Other Asia & Pacific', 'Other CIS', 'Other Caribbean',
       'Other Middle East', 'Other Northern Africa',
       'Other South America', 'Other Southern Africa', 'Pakistan',
       'Palestine', 'Panama', 'Papua New Guinea', 'Paraguay', 'Peru',
       'Philippines', 'Poland', 'Portugal', 'Puerto Rico', 'Qatar',
       'Reunion', 'Romania', 'Russia', 'Rwanda', 'Saint Helena',
       'Saint Kitts and Nevis', 'Saint Lucia',
       'Saint Pierre and Miquelon', 'Saint Vincent and the Grenadines',
       'Samoa', 'Sao Tome and Principe', 'Saudi Arabia', 'Senegal',
       'Serbia', 'Seychelles', 'Sierra Leone', 'Singapore', 'Slovakia',
       'Slovenia', 'Solomon Islands', 'Somalia',
       'South & Central America', 'South Africa', 'South Korea',
       'South Sudan', 'Spain', 'Sri Lanka', 'Sudan', 'Suriname', 'Sweden',
       'Switzerland', 'Syria', 'Taiwan', 'Tajikistan', 'Tanzania',
       'Thailand', 'Togo', 'Tonga', 'Trinidad and Tobago', 'Tunisia',
       'Turkey', 'Turkmenistan', 'Turks and Caicos Islands',
       'U.S. Pacific Islands', 'Uganda', 'Ukraine',
       'United Arab Emirates', 'United Kingdom', 'United States',
       'United States Virgin Islands', 'Uruguay', 'Uzbekistan', 'Vanuatu',
       'Venezuela', 'Vietnam', 'Western Africa', 'Western Sahara',
       'World', 'Yemen', 'Zambia', 'Zimbabwe'], dtype=object)

### 3-VAZIFA. DF dan faqat AQSh (`United States`) uchun ma'lumotlarni ajratib oling va yangi `dfus` nomli o'zgaruvchiga saqlang

In [7]:
# JAVOBNI SHUYERGA YOZING
dfus=df[df.davlat=="United States"]

In [ ]:
#@title Kutilgan natija
dfus.head(6)

             davlat  kod   yil  ...        neft    shamol        atom
5887  United States  USA  1985  ...  107.744380  0.005820  403.884976
5888  United States  USA  1986  ...  146.865448  0.004231  435.829540
5889  United States  USA  1987  ...  127.411367  0.003577  479.231981
5890  United States  USA  1988  ...  160.107055  0.000880  554.708470
5891  United States  USA  1989  ...  176.729591  2.133377  557.215492
5892  United States  USA  1990  ...  135.978712  2.816768  607.222819

[6 rows x 11 columns]

### 4-VAZIFA. `dfus` jadvalining indeksini `yil` ustuni bilan o'zgartiring. DF dan `yil` ustunini tashlab yuboring.

In [9]:
# JAVOBNI SHUYERGA YOZING
dfus.set_index("yil")

,davlat,kod,komir,gaz,gidro,yangilanuvchi,quyosh,neft,shamol,atom
yil,,,,,,,,,,
1985,United States,USA,1507.664651,313.920392,287.182362,36.392894,0.010737,107.744380,0.005820,403.884976
1986,United States,USA,1490.141346,267.213369,296.974969,38.701672,0.014174,146.865448,0.004231,435.829540
1987,United States,USA,1573.958375,293.140648,255.410195,42.665433,0.010603,127.411367,0.003577,479.231981
1988,United States,USA,1656.615886,271.828714,228.384649,42.394061,0.009186,160.107055,0.000880,554.708470
1989,United States,USA,1711.442534,379.170824,274.724178,48.854268,0.253132,176.729591,2.133377,557.215492
1990,United States,USA,1725.155171,400.822746,292.280914,57.459315,0.370795,135.978712,2.816768,607.222819
1991,United States,USA,1722.535851,410.272061,287.326014,60.551763,0.478253,128.765132,2.980759,644.805355
1992,United States,USA,1757.501372,434.488572,251.425678,64.815412,0.408844,107.692648,2.916690,651.343435
1993,United States,USA,1831.210785,446.157847,279.250946,66.924724,0.475162,121.277613,3.036189,642.411804
1994,United States,USA,1832.271952,494.858798,259.341321,66.354857,0.501873,113.872025,3.481928,674.147192
1995,United States,USA,1853.006902,533.395640,311.219815,63.265079,0.514472,80.165661,3.196215,708.844340
1996,United States,USA,1945.754200,489.307071,347.549480,64.825960,0.541341,87.538952,3.266736,710.240575
1997,United States,USA,1998.243409,515.482441,355.973121,65.820084,0.532696,99.521369,3.321247,661.730706
1998,United States,USA,2029.040774,571.244198,322.089274,65.617126,0.524659,138.494810,3.056259,709.160109
1999,United States,USA,2037.863243,598.275405,316.605182,66.477721,0.518342,126.947138,4.533331,766.583288
2000,United States,USA,1966.265000,614.993000,270.034000,74.819000,0.493000,116.015000,5.593000,753.893000
2001,United States,USA,1903.955943,648.168593,208.137599,63.488559,0.542755,136.786564,6.737332,768.826308
2002,United States,USA,1933.130354,702.468431,255.585905,68.200062,0.554831,108.094305,10.354279,780.064087
2003,United States,USA,1973.736750,665.507561,267.271263,67.765320,0.534001,133.450147,11.187467,763.732695
2004,United States,USA,1978.300549,725.352447,259.929098,68.348428,0.575155,135.377458,14.143741,788.528387
2005,United States,USA,2012.873046,774.424398,263.763467,68.968555,0.550294,135.046076,17.810549,781.986365
2006,United States,USA,1990.511135,830.617578,282.688574,69.428650,0.507706,77.140813,26.589137,787.218636
2007,United States,USA,2016.455584,910.043145,240.613622,70.175791,0.611793,77.970109,34.449927,806.424753
2008,United States,USA,1985.801247,894.687475,248.543323,69.873588,0.864315,58.046277,55.363100,806.208435
2009,United States,USA,1755.904253,931.610787,268.817749,69.501392,0.891179,50.864849,73.886132,798.854585
2010,United States,USA,1847.290279,999.010021,254.701937,71.308579,1.212182,49.916355,94.652246,806.968301
2011,United States,USA,1733.430005,1025.255129,312.934388,71.986898,1.817696,44.335845,120.176599,790.204367
2012,United States,USA,1514.042945,1237.791760,271.289723,73.184591,4.326675,36.976608,140.821715,769.331249
2013,United States,USA,1581.114716,1137.688497,263.884350,76.632701,9.035620,40.751966,167.839745,789.016473
2014,United States,USA,1581.710350,1138.630744,253.193074,79.866385,28.923690,43.693157,181.655282,797.165982
2015,United States,USA,1352.398197,1346.598808,243.988597,79.549452,39.032171,42.276556,190.718548,797.177877
2016,United States,USA,1239.148654,1391.114366,261.126026,78.586265,54.866492,37.959041,226.992562,805.693948
2017,United States,USA,1205.835275,1308.883659,293.838608,78.688434,77.276459,34.486074,254.302662,804.949635
2018,United States,USA,1145.962192,1482.189373,286.619450,77.868208,93.364598,38.198843,272.649789,807.084477
2019,United States,USA,964.957000,1598.303000,282.613000,72.980000,106.894000,31.772000,294.906000,809.409262
2020,United States,USA,773.805528,1629.236806,285.789644,72.984923,132.630484,28.947190,336.533331,789.918631

In [ ]:
#@title Kutilgan natija

             davlat  kod        komir  ...        neft    shamol        atom
yil                                    ...
1985  United States  USA  1507.664651  ...  107.744380  0.005820  403.884976
1986  United States  USA  1490.141346  ...  146.865448  0.004231  435.829540
1987  United States  USA  1573.958375  ...  127.411367  0.003577  479.231981
1988  United States  USA  1656.615886  ...  160.107055  0.000880  554.708470
1989  United States  USA  1711.442534  ...  176.729591  2.133377  557.215492

[5 rows x 10 columns]

### 5-VAZIFA. AQSh 2020-yilda jami qancha elektr energiyasi ishlab chiqqan?

In [33]:
# JAVOBNI SHUYERGA YOZING
overAllEnergy=(dfus[dfus.yil==2020].sum(axis=1)-2020)
overAllEnergy.index=dfus[dfus.yil==2020].yil
overAllEnergy

<ipython-input-33-37da5396d63a>:2: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  overAllEnergy=(dfus[dfus.yil==2020].sum(axis=1)-2020)

yil
2020    4049.846537
dtype: float64

In [ ]:
#@title O'xshash natija (2018-yil uchun)

yil
2018    4203.93693
dtype: float64

### 6-VAZIFA. 2010-2020-yillarda AQSH turli manbaalardan o'rtacha qancha elektr toki olganini chiqaring. Natijani kichikdan kattaga qarab tartiblang.

In [51]:
# JAVOBNI SHUYERGA YOZING
filteredDF=dfus.loc[dfus['yil']>=2010]
doubleFiltered=filteredDF.loc[dfus.yil<=2020]
sumValue=doubleFiltered.sum()
result=sumValue.drop(['davlat', 'kod', 'yil'])
result.sort_values()

neft               429.313634
quyosh             549.380066
yangilanuvchi      833.636437
shamol            2281.248479
gidro             3009.978796
atom              8766.920202
gaz              14294.702163
komir            14939.695141
dtype: object

In [ ]:
#@title O'xshash natija (1990-2000 yillar uchun)

quyosh              0.487222
shamol              3.472647
yangilanuvchi      65.175549
neft              114.206278
gidro             299.372340
gaz               500.845253
atom              684.580238
komir            1881.713514
dtype: float64

### 7-VAZIFA. AQSH gidro elektr stansiyalardan eng kam va eng ko'p elektr energiyasi olgan yillarni toping.

In [61]:
df.iloc[dfus['gidro'].idxmax()]

davlat           United States
kod                        USA
yil                       1997
komir              1998.243409
gaz                 515.482441
gidro               355.973121
yangilanuvchi        65.820084
quyosh                0.532696
neft                 99.521369
shamol                3.321247
atom                661.730706
Name: 5899, dtype: object

In [62]:
# JAVOBNI SHUYERGA YOZING
df.iloc[dfus['gidro'].idxmin()]

davlat           United States
kod                        USA
yil                       2001
komir              1903.955943
gaz                 648.168593
gidro               208.137599
yangilanuvchi        63.488559
quyosh                0.542755
neft                136.786564
shamol                6.737332
atom                768.826308
Name: 5903, dtype: object

### 8-VAZIFA.
#### 8.1 Asl `df` dan 2019-yil ma'lumotlarini ajratib oling.
#### 8.2 Yangi df ga `df19` deb nom bering
#### 8.3 `df19` indeksini `davlat` ustuniga o'zgartiring hamda `davlat` va `yil` ustunlarini tashlab yuboring.
#### 8.4 `df19` dan `World` indeksini o'chirib tashlang

In [74]:
# JAVOBNI SHUYERGA YOZING
df19=df[df.yil==2019]
df19=df19.set_index('davlat')
df19=df19.drop(['yil'], axis=1)
df19=df19.drop(['World'])
df19.head(10)

,kod,komir,gaz,gidro,yangilanuvchi,quyosh,neft,shamol,atom
davlat,,,,,,,,,
Afghanistan,AFG,0.000000,0.152000,0.840000,0.000000,0.040000,0.000000,0.000000,0.000000
Africa,NaN,253.555978,340.472820,132.734791,8.184247,19.377978,81.274240,17.508052,14.214193
Albania,ALB,0.000000,0.000000,5.153940,0.000000,0.022000,0.000000,0.000000,0.000000
Algeria,DZA,0.000000,73.615787,0.106440,0.000000,0.615000,0.000000,0.011000,0.000000
American Samoa,ASM,0.000000,0.000000,0.000000,0.000000,0.000000,0.163000,0.000000,0.000000
Angola,AGO,0.000000,1.283610,9.849880,0.252667,0.018000,1.073596,0.000000,0.000000
Antarctica,ATA,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Antigua and Barbuda,ATG,0.000000,0.000000,0.000000,0.000000,0.015000,0.326667,0.000000,0.000000
Argentina,ARG,0.740682,85.786609,27.334890,1.724000,0.800000,3.372430,4.997000,7.927000
Armenia,ARM,0.000000,2.864180,2.347290,0.000000,0.013000,0.000000,0.003000,2.029000

In [ ]:
#@title Kutilgan natija

                     kod       komir  ...     shamol       atom
davlat                                ...
Afghanistan          AFG    0.000000  ...   0.000000   0.000000
Africa               NaN  253.555978  ...  17.508052  14.214193
Albania              ALB    0.000000  ...   0.000000   0.000000
Algeria              DZA    0.000000  ...   0.011000   0.000000
American Samoa       ASM    0.000000  ...   0.000000   0.000000
Angola               AGO    0.000000  ...   0.000000   0.000000
Antarctica           ATA    0.000000  ...   0.000000   0.000000
Antigua and Barbuda  ATG    0.000000  ...   0.000000   0.000000
Argentina            ARG    0.740682  ...   4.997000   7.927000
Armenia              ARM    0.000000  ...   0.003000   2.029000

[10 rows x 9 columns]

#### 8.5 `df19` jadvali uchun umumlashtiruvchi statistikani chiqaring

In [75]:
# JAVOBNI SHUYERGA YOZING
df19.describe()

,komir,gaz,gidro,yangilanuvchi,quyosh,neft,shamol,atom
count,225.000000,225.000000,234.000000,233.000000,234.000000,225.000000,234.000000,234.000000
mean,89.629863,63.570115,40.428494,7.378199,7.297140,10.575434,15.621916,30.370740
std,590.143698,224.662108,169.370944,29.920512,35.365822,36.389645,70.427073,136.481831
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.003195,0.042000,0.000000,0.000000
50%,0.000000,0.229147,0.991647,0.031000,0.040000,0.620333,0.008250,0.000000
75%,4.420929,20.635015,11.910820,1.314232,0.762633,3.872553,1.136484,0.000000
max,7376.390586,1975.752363,1783.656628,238.022873,393.921841,396.115102,514.259616,963.746826

### 9-VAZIFA. 2019-yilda har bir davlat jami qancha elektr energiya ishlab chiqarganini DF ko'rinishida chiqaring.
*ishora. `Series` obyektini `DF` ga o'tkazing

In [76]:
# JAVOBNI SHUYERGA YOZING
df19.sum(axis=1)

<ipython-input-76-1c4b6548ef93>:2: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  df19.sum(axis=1)

davlat
Afghanistan         1.032000
Africa            867.322298
Albania             5.175940
Algeria            74.348227
American Samoa      0.163000
                     ...
Western Africa     20.483381
Western Sahara      0.000000
Yemen               2.513480
Zambia             16.854622
Zimbabwe            9.046100
Length: 234, dtype: float64

In [ ]:
#@title Kutilgan natija

                       max
davlat
Afghanistan       1.032000
Africa          867.322298
Albania           5.175940
Algeria          74.348227
American Samoa    0.163000
...                    ...
Western Africa   20.483381
Western Sahara    0.000000
Yemen             2.513480
Zambia           16.854622
Zimbabwe          9.046100

[234 rows x 1 columns]

### 10-VAZIFA.
#### 10.1. Asl DF dan 2000-2020-yillar, `France` uchun `atom`, `komir`, `gaz`, `quyosh` manbaalarini alohida `dffr` jadvaliga ko'chirib oling
#### 10.2. `dffr` jadvalini yil ustuni bo'yicha tartiblang

In [88]:
# JAVOBNI SHUYERGA YOZING
dffr=df[df.yil>=2000]
dffr=dffr[dffr.yil<=2020]
dffr=dffr[dffr.davlat=="France"]
dffr=dffr.drop(['davlat', 'kod', 'gidro', 'yangilanuvchi', 'shamol', 'neft'], axis=1)
dffr

       yil      komir        gaz     quyosh        atom
1934  2000  27.004000  11.514000   0.005223  415.162000
1935  2001  20.478000  15.146000   0.006161  421.076000
1936  2002  23.658000  18.369000   0.007104  436.760000
1937  2003  26.260000  19.368000   0.007767  441.070000
1938  2004  24.372000  21.049000   0.008448  448.241000
1939  2005  27.515000  23.069000   0.010501  451.529000
1940  2006  22.889000  21.760000   0.012103  450.191000
1941  2007  24.446000  21.987000   0.017572  439.730000
1942  2008  23.063000  21.884000   0.041692  439.447000
1943  2009  21.667000  20.503000   0.173971  409.736000
1944  2010  23.359000  23.758000   0.620000  428.521000
1945  2011  17.807444  29.489144   2.333802  442.387763
1946  2012  21.449981  22.753254   4.427930  425.406017
1947  2013  23.830994  18.393269   5.193590  423.684671
1948  2014  11.242305  13.162876   6.391477  436.479009
1949  2015  11.873673  21.143153   7.753328  437.427808
1950  2016  10.344460  34.967086   8.659160  403.195482
1951  2017  12.818153  40.500366   9.584882  398.359129
1952  2018   8.412694  30.587768  10.568737  412.941812
1953  2019   4.412694  37.587768  12.568737  398.941812
1954  2020   4.275487  34.245560  13.190057  355.190804

In [ ]:
#@title Kutilgan natija

       yil        atom      komir        gaz     quyosh
1934  2000  415.162000  27.004000  11.514000   0.005223
1935  2001  421.076000  20.478000  15.146000   0.006161
1936  2002  436.760000  23.658000  18.369000   0.007104
1937  2003  441.070000  26.260000  19.368000   0.007767
1938  2004  448.241000  24.372000  21.049000   0.008448
1939  2005  451.529000  27.515000  23.069000   0.010501
1940  2006  450.191000  22.889000  21.760000   0.012103
1941  2007  439.730000  24.446000  21.987000   0.017572
1942  2008  439.447000  23.063000  21.884000   0.041692
1943  2009  409.736000  21.667000  20.503000   0.173971
1944  2010  428.521000  23.359000  23.758000   0.620000
1945  2011  442.387763  17.807444  29.489144   2.333802
1946  2012  425.406017  21.449981  22.753254   4.427930
1947  2013  423.684671  23.830994  18.393269   5.193590
1948  2014  436.479009  11.242305  13.162876   6.391477
1949  2015  437.427808  11.873673  21.143153   7.753328
1950  2016  403.195482  10.344460  34.967086   8.659160
1951  2017  398.359129  12.818153  40.500366   9.584882
1952  2018  412.941812   8.412694  30.587768  10.568737
1953  2019  398.941812   4.412694  37.587768  12.568737
1954  2020  355.190804   4.275487  34.245560  13.190057

#### 10.3 `dffr`uchun Korrelyasiya jadvalini chiqaring.

In [89]:
# JAVOBNI SHUYERGA YOZING
dffr.corr()

             yil     komir       gaz    quyosh      atom
yil     1.000000 -0.866541  0.732072  0.918831 -0.606801
komir  -0.866541  1.000000 -0.665521 -0.933234  0.677929
gaz     0.732072 -0.665521  1.000000  0.706133 -0.561700
quyosh  0.918831 -0.933234  0.706133  1.000000 -0.726689
atom   -0.606801  0.677929 -0.561700 -0.726689  1.000000